#!/bin/sh

## Show network status

# Show Wi-Fi received signal strength (fancy!)
WLAN_LEVEL=$(awk '/^w/ { print int($4) "dBm"}' /proc/net/wireless)

if [ -z $WLAN_LEVEL ]; then WLAN_LEVEL="DOWN"; fi

echo "WLAN:$WLAN_LEVEL"
